version: "3.9"
services:
  db:
    build:
      context: ./db
    image: postgres-container
    container_name: db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
    image: app-container
    container_name: app_container
    depends_on:
      - db
    networks:
      - app_network
    command: ["python", "main.py"]

volumes:
  db_data:

networks:
  app_network:
    driver: bridge